### ISSUE TITLE
If movie title begins with a capital letter, no movie is found

### ISSUE THREAD

**Issue by ulysseskan** [nmcassa/letterboxdpy#6]
If you begin the movie title with a capital letter, for example:

```
if __name__ == "__main__":
    king = Movie("King kong")
    print(king)
```

You get:
```
...
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/letterboxdpy/movie.py", line 178, in <module>
    king = Movie("King kong")
  File "/opt/homebrew/lib/python3.10/site-packages/letterboxdpy/movie.py", line 25, in __init__
    self.movie_genre(page)
  File "/opt/homebrew/lib/python3.10/site-packages/letterboxdpy/movie.py", line 91, in movie_genre
    raise Exception("No movie found")
Exception: No movie found
```

To resolve, you could either update the README to reflect this or update https://github.com/nmcassa/letterboxdpy/blob/main/src/letterboxdpy/movie.py#L14 to  automatically convert the title to lowercase with:

```self.title = title.replace(' ', '-').lower()```

**Comment by nmcassa** [comment]
Thanks for pointing this out!
